# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adaravis/releases/download/2024.4.2/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: gige camera 01

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: "GMT0BST"

  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 3000000

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADAravis.aravisCamera
    CLASS: AVT_Manta_G895B
    P: BLEC1-EA-DET-01
    R: ":DET:"
    # local connection to laptop
    ID: "169.254.246.2"
    # controls dev network
    # ID: "172.23.243.42"
    PORT: DET.CAM

  - type: ADCore.NDPvaPlugin
    P: BLEC1-EA-DET-01
    R: ":TX:"
    PORT: DET.PVA
    NDARRAY_PORT: DET.CAM
    PVNAME: BLEC1-EA-DET-01:TX:PVA

  - type: ADCore.NDFileHDF5
    ENABLED: 1
    NDARRAY_PORT: DET.CAM
    P: BLEC1-EA-DET-01
    PORT: DET.HDF
    R: ":HDF5:"

  - type: ADCore.NDFileTIFF
    P: BLEC1-EA-DET-01
    R: ":TIFF:"
    PORT: DET.TIFF
    NDARRAY_PORT: DET.CAM

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:AcquireTime
    value: "0.005"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:SizeX
    value: "1024"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:SizeY
    value: "1024"
    
  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:FilePath
    value: "/data"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:FileTemplate
    value: "%s%s%05d.h5"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:EnableCallbacks
    value: "1"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:CreateDirectory
    value: "1"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:FileWriteMode
    value: "Stream"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:AutoIncrement
    value: "1"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:NumCapture
    value: "20"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:BinX
    value: "2"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:BinX
    value: "2"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:MinX
    value: "512"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:MinY
    value: "512"


  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:HDF5:NumCapture
    value: "320"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:GC_GevSCPSPacketSize
    value: "1500"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:TX:EnableCallbacks
    value: "1"

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:AcquirePeriod
    value: "0.064"

  # use FreeRun to turn off triggering
  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:TriggerSource
    # use Line1 for triggering by PandaBox
    value: Line1
    # use Freerun for continuous acquisition
    # value: Freerun

  - type: epics.dbpf
    pv: BLEC1-EA-DET-01:DET:Acquire
    value: "1"
