# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.0
_src_path: gh:epics-containers/ec-services-template
beamline: bl-ec-test
cluster_namespace: local
description: beamline bl-ec-test IOC Instances and Services
git_platform: github.com
github_org: epics-containers
repo_uri: git@github.com:epics-containers/bl-ec-test.git
type: beamline
